/*     */ package com.mchange.v2.c3p0.stmt;
/*     */ 
/*     */ import com.mchange.v2.coalesce.CoalesceChecker;
/*     */ import com.mchange.v2.coalesce.Coalescer;
/*     */ import com.mchange.v2.coalesce.CoalescerFactory;
/*     */ import java.lang.reflect.Method;
/*     */ import java.sql.Connection;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ final class ValueIdentityStatementCacheKey
/*     */   extends StatementCacheKey
/*     */ {
/*     */   static final Coalescer keyCoalescer;
/*  43 */   static ValueIdentityStatementCacheKey spare = new ValueIdentityStatementCacheKey();
/*     */   int cached_hash;
/*     */   
/*     */   static {
/*  47 */     CoalesceChecker cc = new CoalesceChecker()
/*     */     {
/*     */       public boolean checkCoalesce(Object a, Object b) {
/*  50 */         return StatementCacheKey.equals((StatementCacheKey)a, b);
/*     */       }
/*     */       
/*  53 */       public int coalesceHash(Object a) { return ((ValueIdentityStatementCacheKey)a).cached_hash;
/*     */       }
/*     */ 
/*  56 */     };
/*  57 */     keyCoalescer = CoalescerFactory.createCoalescer(cc, true, false);
/*     */   }
/*     */   
/*     */ 
/*     */   static StatementCacheKey _find(Connection pcon, Method stmtProducingMethod, Object[] args)
/*     */   {
/*  63 */     String stmtText = (String)args[0];
/*  64 */     boolean is_callable = stmtProducingMethod.getName().equals("prepareCall");
/*     */     
/*     */ 
/*     */ 
/*     */ 
/*     */     Integer resultSetHoldability;
/*     */     
/*     */ 
/*     */ 
/*  73 */     if (args.length == 1)
/*     */     {
/*  75 */       int result_set_type = 1003;
/*  76 */       int result_set_concurrency = 1007;
/*  77 */       int[] columnIndexes = null;
/*  78 */       String[] columnNames = null;
/*  79 */       Integer autogeneratedKeys = null;
/*  80 */       resultSetHoldability = null;
/*     */     } else { Integer resultSetHoldability;
/*  82 */       if (args.length == 2)
/*     */       {
/*  84 */         Class[] argTypes = stmtProducingMethod.getParameterTypes();
/*  85 */         Integer resultSetHoldability; Integer autogeneratedKeys; String[] columnNames; int[] columnIndexes; int result_set_concurrency; int result_set_type; if (argTypes[1].isArray())
/*     */         {
/*  87 */           Class baseType = argTypes[1].getComponentType();
/*  88 */           Integer resultSetHoldability; if (baseType == Integer.TYPE)
/*     */           {
/*  90 */             int result_set_type = 1003;
/*  91 */             int result_set_concurrency = 1007;
/*  92 */             int[] columnIndexes = (int[])args[1];
/*  93 */             String[] columnNames = null;
/*  94 */             Integer autogeneratedKeys = null;
/*  95 */             resultSetHoldability = null;
/*     */           } else { Integer resultSetHoldability;
/*  97 */             if (baseType == String.class)
/*     */             {
/*  99 */               int result_set_type = 1003;
/* 100 */               int result_set_concurrency = 1007;
/* 101 */               int[] columnIndexes = null;
/* 102 */               String[] columnNames = (String[])args[1];
/* 103 */               Integer autogeneratedKeys = null;
/* 104 */               resultSetHoldability = null;
/*     */             }
/*     */             else {
/* 107 */               throw new IllegalArgumentException("c3p0 probably needs to be updated for some new JDBC spec! As of JDBC3, we expect two arg statement producing methods where the second arg is either an int, int array, or String array.");
/*     */             }
/*     */             
/*     */           }
/*     */         }
/*     */         else
/*     */         {
/* 114 */           int result_set_type = 1003;
/* 115 */           int result_set_concurrency = 1007;
/* 116 */           int[] columnIndexes = null;
/* 117 */           String[] columnNames = null;
/* 118 */           Integer autogeneratedKeys = (Integer)args[1];
/* 119 */           resultSetHoldability = null;
/*     */         }
/*     */       } else { Integer resultSetHoldability;
/* 122 */         if (args.length == 3)
/*     */         {
/* 124 */           int result_set_type = ((Integer)args[1]).intValue();
/* 125 */           int result_set_concurrency = ((Integer)args[2]).intValue();
/* 126 */           int[] columnIndexes = null;
/* 127 */           String[] columnNames = null;
/* 128 */           Integer autogeneratedKeys = null;
/* 129 */           resultSetHoldability = null;
/*     */         } else { Integer resultSetHoldability;
/* 131 */           if (args.length == 4)
/*     */           {
/* 133 */             int result_set_type = ((Integer)args[1]).intValue();
/* 134 */             int result_set_concurrency = ((Integer)args[2]).intValue();
/* 135 */             int[] columnIndexes = null;
/* 136 */             String[] columnNames = null;
/* 137 */             Integer autogeneratedKeys = null;
/* 138 */             resultSetHoldability = (Integer)args[3];
/*     */           }
/*     */           else {
/* 141 */             throw new IllegalArgumentException("Unexpected number of args to " + stmtProducingMethod.getName());
/*     */           }
/*     */         } } }
/*     */     Integer resultSetHoldability;
/*     */     Integer autogeneratedKeys;
/*     */     String[] columnNames;
/*     */     int[] columnIndexes;
/*     */     int result_set_concurrency;
/*     */     int result_set_type;
/* 150 */     spare.init(pcon, stmtText, is_callable, result_set_type, result_set_concurrency, columnIndexes, columnNames, autogeneratedKeys, resultSetHoldability);
/*     */     
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/* 160 */     StatementCacheKey out = (StatementCacheKey)keyCoalescer.coalesce(spare);
/*     */     
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/* 166 */     if (out == spare)
/* 167 */       spare = new ValueIdentityStatementCacheKey();
/* 168 */     return out;
/*     */   }
/*     */   
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   void init(Connection physicalConnection, String stmtText, boolean is_callable, int result_set_type, int result_set_concurrency, int[] columnIndexes, String[] columnNames, Integer autogeneratedKeys, Integer resultSetHoldability)
/*     */   {
/* 181 */     super.init(physicalConnection, stmtText, is_callable, result_set_type, result_set_concurrency, columnIndexes, columnNames, autogeneratedKeys, resultSetHoldability);
/*     */     
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/* 190 */     this.cached_hash = StatementCacheKey.hashCode(this);
/*     */   }
/*     */ }


/* Location:              E:\BaiduYunDownload\伊萨时期的一些代码\SparkEngine终极版\jars\YISAEngineBySpark2-4.0.6-SNAPSHOT-jar-with-dependencies.jar!\com\mchange\v2\c3p0\stmt\ValueIdentityStatementCacheKey.class
 * Java compiler version: 4 (48.0)
 * JD-Core Version:       0.7.1
 */